version: "3.9"
services:
  ros2:
    build: .
    network_mode: host
    ipc: host
    volumes:
      - /home/carbi/ros:/home/ros
      - /home/carbi/CARBI-1:/ros2
    privileged: true
    devices:
#      - /dev:/dev
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyUSB2:/dev/ttyUSB2
      - /dev/i2c-1:/dev/i2c-1
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    restart: always
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    tty: true
    environment:
      - DISPLAY
